import moment from 'moment';
export const cardInitialState = {
    PATH: '',
    RPATH: '',
    GIF: '',
    NAME: '',
    PRICE: 0,
    TOURNAMENT_REQUIREMENTS: 0,
    MOVESET: {},
    HLT: 500,
    STAM: 100,
    ATK: 50,
    DEF: 70,
    TYPE: 0,
    ACC: 0.5,
    PASS: [],
    SPD: .5,
    VUL: false,
    UNIVERSE: '',
    COLLECTION: '',
    HAS_COLLECTION: null,
    STOCK: 10,
    AVAILABLE: false,
    DESCRIPTIONS: [],
    EXCLUSIVE: false
}

export const enhancements = [
    'ATK',
    'DEF',
    'STAM',
    'HLT',
    'LIFE',
    'DRAIN',
    'FLOG',
    'WITHER',
    'RAGE',
    'BRACE',
    'BZRK',
    'CRYSTAL',
    'GROWTH',
    'STANCE',
    'CONFUSE',
    'BLINK',
    'SLOW',
    'HASTE',
    'SOULCHAIN',
    'GAMBLE',
    'FEAR',
    'WAVE',
    'BLAST',
    'CREATION',
    'DESTRUCTION'
]
